[project]
name = "httprexx"
version = "1.0.0-dev"
type = "module"

[build]
cflags = [
	"-O1",
]

[build.sources]
c_dirs = ["src/"]

[mvs.build.datasets.source]
suffix = "SOURCE"
dsorg = "PO"
recfm = "FB"
lrecl = 80
blksize = 19040
space = ["TRK", 30, 10, 20]

[mvs.build.datasets.punch]
suffix = "OBJECT"
dsorg = "PO"
recfm = "FB"
lrecl = 80
blksize = 19040
space = ["TRK", 20, 10, 20]

[mvs.build.datasets.ncalib]
suffix = "NCALIB"
dsorg = "PO"
recfm = "U"
lrecl = 0
blksize = 19069
space = ["TRK", 20, 10, 20]

[mvs.build.datasets.syslmod]
suffix = "LOAD"
dsorg = "PO"
recfm = "U"
lrecl = 0
blksize = 15040
space = ["TRK", 20, 10, 5]

[dependencies]
"mvslovers/crent370" = ">=1.0.9"
"mvslovers/httpd" = "=4.0.0-dev"

# --- Load Modules ------------------------------------------------

# BREXX say helper (@@CRTM instead of @@CRT1)
[[link.module]]
name = "HTTPSAY"
entry = "@@CRT0"
options = ["LIST", "MAP", "XREF", "RENT"]
include = ["@@CRTM", "HTTPSAY"]

# REXX CGI handler
[[link.module]]
name = "HTTPREXX"
entry = "@@CRT0"
options = ["LIST", "MAP", "XREF", "RENT"]
include = ["@@CRT1", "CGISTART", "HTTPREXX"]

[release]
version_files = ["VERSION"]
